version: "3.8"
   
services:
  web:
    build: ./app
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - /usr/src/app
    environment:
      - DB_HOST= "db"
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/assets/idrl-videos-202410-88905e13ff46.json
    ports:
      - "5000:5000"
    networks:
      - default
    env_file:
      - ./.env.prod
    restart: always
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    restart: always
  worker:
    build:
      context: ./celery
    volumes:
      - ./videos:/usr/src/app/videos/
    command: python -u /usr/src/celery/tasks.py
    restart: always
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/celery/assets/idrl-videos-202410-88905e13ff46.json
  
  
