version: "3.8"
   
services:
  redis:
    image: 'redis'
    ports:
      - "6379:6379"
    restart: always
  worker:
    build:
      context: ./celery
    command: celery -A tasks worker -l info -E
    volumes:
      - ./videos:/usr/src/app/videos/
    depends_on:
      - redis
    restart: always
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/assets/idrl-videos-202410-88905e13ff46.json
  
  
